# Configuração do PostgreSQL para o Sistema NFSe
version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15
    container_name: nfse_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: nfse_sistema
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    networks:
      - nfse_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PgAdmin para gerenciamento visual do banco (opcional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nfse_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nfse.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nfse_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  nfse_network:
    driver: bridge